{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [],
   "source": [
    "creds = 'client_secret.json'\n",
    "# https://www.jcchouinard.com/google-api/\n",
    "\n",
    "site = 'https://www.jcchouinard.com'\n",
    "start_date = '2022-01-01' \n",
    "end_date = '2020-01-30' # Default: 3d in past\n",
    "output = 'gsc_data.csv'\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Collecting certifi==2020.4.5.1\n",
      "  Using cached certifi-2020.4.5.1-py2.py3-none-any.whl (157 kB)\n",
      "Collecting google-api-python-client==1.8.3\n",
      "  Using cached google_api_python_client-1.8.3-py3-none-any.whl (58 kB)\n",
      "Collecting google-auth==1.15.0\n",
      "  Using cached google_auth-1.15.0-py2.py3-none-any.whl (89 kB)\n",
      "Collecting google-auth-httplib2==0.0.3\n",
      "  Using cached google_auth_httplib2-0.0.3-py2.py3-none-any.whl (6.3 kB)\n",
      "Collecting google-auth-oauthlib==0.4.1\n",
      "  Using cached google_auth_oauthlib-0.4.1-py2.py3-none-any.whl (18 kB)\n",
      "Collecting httplib2==0.18.1\n",
      "  Using cached httplib2-0.18.1-py3-none-any.whl (95 kB)\n",
      "Collecting idna==2.6\n",
      "  Using cached idna-2.6-py2.py3-none-any.whl (56 kB)\n",
      "Collecting oauth2client==4.1.2\n",
      "  Using cached oauth2client-4.1.2-py2.py3-none-any.whl (99 kB)\n",
      "Collecting oauthlib==3.1.0\n",
      "  Using cached oauthlib-3.1.0-py2.py3-none-any.whl (147 kB)\n",
      "Collecting pyasn1==0.4.2\n",
      "  Using cached pyasn1-0.4.2-py2.py3-none-any.whl (71 kB)\n",
      "Collecting pyasn1-modules==0.2.1\n",
      "  Using cached pyasn1_modules-0.2.1-py2.py3-none-any.whl (60 kB)\n",
      "Collecting requests==2.23.0\n",
      "  Using cached requests-2.23.0-py2.py3-none-any.whl (58 kB)\n",
      "Collecting requests-oauthlib==0.8.0\n",
      "  Using cached requests_oauthlib-0.8.0-py2.py3-none-any.whl (23 kB)\n",
      "Collecting rsa==3.4.2\n",
      "  Using cached rsa-3.4.2-py2.py3-none-any.whl (46 kB)\n",
      "Collecting uritemplate==3.0.0\n",
      "  Using cached uritemplate-3.0.0-py2.py3-none-any.whl (10 kB)\n",
      "Collecting urllib3==1.25.9\n",
      "  Using cached urllib3-1.25.9-py2.py3-none-any.whl (126 kB)\n",
      "Requirement already satisfied: python-dateutil==2.8.1 in /Users/l.reddy/opt/anaconda3/lib/python3.8/site-packages (from -r requirements.txt (line 17)) (2.8.1)\n",
      "Requirement already satisfied: pandas in /Users/l.reddy/opt/anaconda3/lib/python3.8/site-packages (from -r requirements.txt (line 18)) (1.2.4)\n",
      "Requirement already satisfied: six<2dev,>=1.6.1 in /Users/l.reddy/opt/anaconda3/lib/python3.8/site-packages (from google-api-python-client==1.8.3->-r requirements.txt (line 2)) (1.12.0)\n",
      "Requirement already satisfied: google-api-core<2dev,>=1.13.0 in /Users/l.reddy/opt/anaconda3/lib/python3.8/site-packages (from google-api-python-client==1.8.3->-r requirements.txt (line 2)) (1.31.0)\n",
      "Requirement already satisfied: cachetools<5.0,>=2.0.0 in /Users/l.reddy/opt/anaconda3/lib/python3.8/site-packages (from google-auth==1.15.0->-r requirements.txt (line 3)) (4.2.2)\n",
      "Requirement already satisfied: setuptools>=40.3.0 in /Users/l.reddy/opt/anaconda3/lib/python3.8/site-packages (from google-auth==1.15.0->-r requirements.txt (line 3)) (52.0.0.post20210125)\n",
      "Requirement already satisfied: chardet<4,>=3.0.2 in /Users/l.reddy/opt/anaconda3/lib/python3.8/site-packages (from requests==2.23.0->-r requirements.txt (line 12)) (3.0.4)\n",
      "Requirement already satisfied: protobuf>=3.12.0 in /Users/l.reddy/opt/anaconda3/lib/python3.8/site-packages (from google-api-core<2dev,>=1.13.0->google-api-python-client==1.8.3->-r requirements.txt (line 2)) (3.19.4)\n",
      "Collecting google-api-core<2dev,>=1.13.0\n",
      "  Using cached google_api_core-1.31.5-py2.py3-none-any.whl (93 kB)\n",
      "  Using cached google_api_core-1.31.4-py2.py3-none-any.whl (93 kB)\n",
      "  Using cached google_api_core-1.31.3-py2.py3-none-any.whl (93 kB)\n",
      "Collecting protobuf<3.18.0,>=3.12.0\n",
      "  Using cached protobuf-3.17.3-cp38-cp38-macosx_10_9_x86_64.whl (1.0 MB)\n",
      "Collecting google-api-core<2dev,>=1.13.0\n",
      "  Using cached google_api_core-1.31.2-py2.py3-none-any.whl (93 kB)\n",
      "  Using cached google_api_core-1.31.1-py2.py3-none-any.whl (93 kB)\n",
      "  Using cached google_api_core-1.30.0-py2.py3-none-any.whl (93 kB)\n",
      "  Using cached google_api_core-1.29.0-py2.py3-none-any.whl (93 kB)\n",
      "  Using cached google_api_core-1.28.0-py2.py3-none-any.whl (92 kB)\n",
      "  Using cached google_api_core-1.27.0-py2.py3-none-any.whl (93 kB)\n",
      "  Using cached google_api_core-1.26.3-py2.py3-none-any.whl (93 kB)\n",
      "  Using cached google_api_core-1.26.2-py2.py3-none-any.whl (93 kB)\n",
      "  Using cached google_api_core-1.26.1-py2.py3-none-any.whl (92 kB)\n",
      "  Using cached google_api_core-1.26.0-py2.py3-none-any.whl (92 kB)\n",
      "  Using cached google_api_core-1.25.1-py2.py3-none-any.whl (92 kB)\n",
      "  Using cached google_api_core-1.25.0-py2.py3-none-any.whl (92 kB)\n",
      "  Using cached google_api_core-1.24.1-py2.py3-none-any.whl (92 kB)\n",
      "  Using cached google_api_core-1.24.0-py2.py3-none-any.whl (91 kB)\n",
      "  Using cached google_api_core-1.23.0-py2.py3-none-any.whl (91 kB)\n",
      "  Using cached google_api_core-1.22.4-py2.py3-none-any.whl (91 kB)\n",
      "  Using cached google_api_core-1.22.3-py2.py3-none-any.whl (91 kB)\n",
      "  Using cached google_api_core-1.22.2-py2.py3-none-any.whl (91 kB)\n",
      "  Using cached google_api_core-1.22.1-py2.py3-none-any.whl (91 kB)\n",
      "  Using cached google_api_core-1.22.0-py2.py3-none-any.whl (91 kB)\n",
      "  Using cached google_api_core-1.21.0-py2.py3-none-any.whl (90 kB)\n",
      "  Using cached google_api_core-1.20.1-py2.py3-none-any.whl (90 kB)\n",
      "Requirement already satisfied: googleapis-common-protos<2.0dev,>=1.6.0 in /Users/l.reddy/opt/anaconda3/lib/python3.8/site-packages (from google-api-core<2dev,>=1.13.0->google-api-python-client==1.8.3->-r requirements.txt (line 2)) (1.53.0)\n",
      "Requirement already satisfied: pytz in /Users/l.reddy/opt/anaconda3/lib/python3.8/site-packages (from google-api-core<2dev,>=1.13.0->google-api-python-client==1.8.3->-r requirements.txt (line 2)) (2021.1)\n",
      "Requirement already satisfied: numpy>=1.16.5 in /Users/l.reddy/opt/anaconda3/lib/python3.8/site-packages (from pandas->-r requirements.txt (line 18)) (1.19.5)\n",
      "Installing collected packages: pyasn1, urllib3, rsa, pyasn1-modules, idna, certifi, requests, oauthlib, httplib2, google-auth, uritemplate, requests-oauthlib, google-auth-httplib2, google-api-core, oauth2client, google-auth-oauthlib, google-api-python-client\n",
      "  Attempting uninstall: pyasn1\n",
      "    Found existing installation: pyasn1 0.4.8\n",
      "    Uninstalling pyasn1-0.4.8:\n",
      "      Successfully uninstalled pyasn1-0.4.8\n",
      "  Attempting uninstall: urllib3\n",
      "    Found existing installation: urllib3 1.24.2\n",
      "    Uninstalling urllib3-1.24.2:\n",
      "      Successfully uninstalled urllib3-1.24.2\n",
      "  Attempting uninstall: rsa\n",
      "    Found existing installation: rsa 4.7.2\n",
      "    Uninstalling rsa-4.7.2:\n",
      "      Successfully uninstalled rsa-4.7.2\n",
      "  Attempting uninstall: pyasn1-modules\n",
      "    Found existing installation: pyasn1-modules 0.2.8\n",
      "    Uninstalling pyasn1-modules-0.2.8:\n",
      "      Successfully uninstalled pyasn1-modules-0.2.8\n",
      "  Attempting uninstall: idna\n",
      "    Found existing installation: idna 2.8\n",
      "    Uninstalling idna-2.8:\n",
      "      Successfully uninstalled idna-2.8\n",
      "  Attempting uninstall: certifi\n",
      "    Found existing installation: certifi 2019.9.11\n",
      "    Uninstalling certifi-2019.9.11:\n",
      "      Successfully uninstalled certifi-2019.9.11\n",
      "  Attempting uninstall: requests\n",
      "    Found existing installation: requests 2.22.0\n",
      "    Uninstalling requests-2.22.0:\n",
      "      Successfully uninstalled requests-2.22.0\n",
      "  Attempting uninstall: httplib2\n",
      "    Found existing installation: httplib2 0.19.1\n",
      "    Uninstalling httplib2-0.19.1:\n",
      "      Successfully uninstalled httplib2-0.19.1\n",
      "  Attempting uninstall: google-auth\n",
      "    Found existing installation: google-auth 1.33.0\n",
      "    Uninstalling google-auth-1.33.0:\n",
      "      Successfully uninstalled google-auth-1.33.0\n",
      "  Attempting uninstall: uritemplate\n",
      "    Found existing installation: uritemplate 3.0.1\n",
      "    Uninstalling uritemplate-3.0.1:\n",
      "      Successfully uninstalled uritemplate-3.0.1\n",
      "  Attempting uninstall: google-auth-httplib2\n",
      "    Found existing installation: google-auth-httplib2 0.1.0\n",
      "    Uninstalling google-auth-httplib2-0.1.0:\n",
      "      Successfully uninstalled google-auth-httplib2-0.1.0\n",
      "  Attempting uninstall: google-api-core\n",
      "    Found existing installation: google-api-core 1.31.0\n",
      "    Uninstalling google-api-core-1.31.0:\n",
      "      Successfully uninstalled google-api-core-1.31.0\n",
      "  Attempting uninstall: oauth2client\n",
      "    Found existing installation: oauth2client 4.0.0\n",
      "    Uninstalling oauth2client-4.0.0:\n",
      "      Successfully uninstalled oauth2client-4.0.0\n",
      "  Attempting uninstall: google-api-python-client\n",
      "    Found existing installation: google-api-python-client 2.14.0\n",
      "    Uninstalling google-api-python-client-2.14.0:\n",
      "      Successfully uninstalled google-api-python-client-2.14.0\n",
      "\u001b[31mERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.\n",
      "conda-repo-cli 1.0.4 requires pathlib, which is not installed.\n",
      "piwik-api 0.1.2 requires requests==2.18.1, but you have requests 2.23.0 which is incompatible.\n",
      "google-cloud-core 2.2.2 requires google-api-core<3.0.0dev,>=1.21.0, but you have google-api-core 1.20.1 which is incompatible.\n",
      "google-cloud-core 2.2.2 requires google-auth<3.0dev,>=1.24.0, but you have google-auth 1.15.0 which is incompatible.\n",
      "google-cloud-bigquery 2.32.0 requires google-api-core[grpc]<3.0.0dev,>=1.29.0, but you have google-api-core 1.20.1 which is incompatible.\n",
      "anyio 2.2.0 requires idna>=2.8, but you have idna 2.6 which is incompatible.\u001b[0m\n",
      "Successfully installed certifi-2020.4.5.1 google-api-core-1.20.1 google-api-python-client-1.8.3 google-auth-1.15.0 google-auth-httplib2-0.0.3 google-auth-oauthlib-0.4.1 httplib2-0.18.1 idna-2.6 oauth2client-4.1.2 oauthlib-3.1.0 pyasn1-0.4.2 pyasn1-modules-0.2.1 requests-2.23.0 requests-oauthlib-0.8.0 rsa-3.4.2 uritemplate-3.0.0 urllib3-1.25.9\n"
     ]
    }
   ],
   "source": [
    "!pip install -r requirements.txt\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [
    {
     "ename": "ImportError",
     "evalue": "cannot import name 'authorize_creds' from 'oauth' (/Users/l.reddy/opt/anaconda3/lib/python3.8/site-packages/oauth/__init__.py)",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mImportError\u001b[0m                               Traceback (most recent call last)",
      "\u001b[0;32m<ipython-input-1-99dcfba70625>\u001b[0m in \u001b[0;36m<module>\u001b[0;34m\u001b[0m\n\u001b[0;32m----> 1\u001b[0;31m \u001b[0;32mfrom\u001b[0m \u001b[0moauth\u001b[0m \u001b[0;32mimport\u001b[0m \u001b[0mauthorize_creds\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m      2\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m      3\u001b[0m \u001b[0mwebmasters_service\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mauthorize_creds\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mcreds\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;31mImportError\u001b[0m: cannot import name 'authorize_creds' from 'oauth' (/Users/l.reddy/opt/anaconda3/lib/python3.8/site-packages/oauth/__init__.py)"
     ]
    }
   ],
   "source": [
    "from oauth import authorize_creds\n",
    "\n",
    "webmasters_service = authorize_creds(creds)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.8"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
